name: Test Dependency Submission

on: [push]

permissions:
  contents: read
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: mvn dependency:tree
    - uses: advanced-security/maven-dependency-submission-action@v3
      with:
        ignore-maven-wrapper: true
